function zoom(n) {
  if (n == 1) {
    hinh.width = 300;
    hinh.height = 400;
  } else {
    hinh.width = 900;
    hinh.height = 600;
  }
}

var product = [
  {
    pid: 3,
    src: "/Picture/hoagiabo1.png",
    title: "Hoa hồng giả mix xanh đỏ",
    content: 25000,
    mota: "hoa được làm từ nhựa dẻo, màu sắc tươi mới và hương thơm nhân tạo an toàn với sức khoer",
    detail: "1",
    new: 1,
    discount: 0.9,
  },
  {
    pid: 3,
    src: "/Picture/hjoagiabo2.png",
    title: "Hoa hồng giả mix đỏ trắng ",
    content: 25000,
    mota: "hoa được làm từ nhựa dẻ và vải lụa, màu sắc tươi mới và hương thơm nhân tạo an toàn với sức khoer",
    detail: "2",
    new: 0,
    discount: 0,
  },
  {
    pid: 3,
    src: "/Picture/hoagiabo3.png",
    title: "Hoa tuylip mix hoa lau trắng",
    content: 25000,
    mota: "hoa nhựa được cố định chắc chắn, màu sắc tươi mới và hương thơm nhân tạo an toàn với sức khoer",
    detail: "3",
    new: 0,
    discount: 0,
  },
  {
    pid: 3,
    src: "/Picture/hoagiabo4.png",
    title: "Cẩm tú cầu mix hoa cúc",
    content: 25000,
    mota: "hoa được làm từ nhựa, màu sắc tươi mới và hương thơm nhân tạo an toàn với sức khoer",
    detail: "4",
    new: 0,
    discount: 0,
  },
  {
    pid: 2,
    src: "/Picture/hoagiabo5.png",
    title: "Hoa cúc giấy",
    content: 25000,
    mota: "hoa được làm từ nhựa dẻo, màu sắc tươi mới và hương thơm nhân tạo an toàn với sức khoer",
    detail: "5",
    new: 0,
    discount: 0.85,
  },
  {
    pid: 2,
    src: "/Picture/hoagiay1.png",
    title: "Hoa hồng giấy",
    content: 25000,
    mota: "hoa được làm từ nhựa dẻo, màu sắc tươi mới và hương thơm nhân tạo an toàn với sức khoer",
    detail: "6",
    new: 1,
    discount: 0.85,
  },
  {
    pid: 2,
    src: "/Picture/hoagiabo7.png",
    title: "Hoa sao giấy",
    content: 25000,
    mota: "hoa được làm từ nhựa dẻo, màu sắc tươi mới và hương thơm nhân tạo an toàn với sức khoer",
    detail: "7",
    new: 1,
    discount: 0.9,
  },
  {
    pid: 2,
    src: "/Picture/hoagiay2.png",
    title: "Hoa hồng giấy",
    content: 25000,
    mota: "hoa được làm từ nhựa dẻo, màu sắc tươi mới và hương thơm nhân tạo an toàn với sức khoer",
    detail: "8",
    new: 0,
    discount: 0,
  },
  {
    pid: 4,
    src: "/Picture/hoagia1.png",
    title: "Hướng dương",
    content: 25000,
    mota: "hoa được làm từ nhựa dẻo, màu sắc tươi mới và hương thơm nhân tạo an toàn với sức khoer",
    detail: "9",
    new: 0,
    discount: 0,
  },
  {
    pid: 4,
    src: "/Picture/hoagia2.png",
    title: "Mẫu đơn lẻ",
    content: 25000,
    mota: "hoa được làm từ nhựa dẻo, màu sắc tươi mới 1 nhánh lớn gồm 5 nhánh nhỏ",
    detail: "10",
    new: 0,
    discount: 0,
  },
  {
    pid: 4,
    src: "/Picture/hoagia3.png",
    title: "Lay ơn lẻ",
    content: 25000,
    mota: "hoa được làm từ nhựa dẻo, có mùi hương nhân tạo an toàn cho sức khỏe 1 pack gồm 4 hoa nhỏ",
    detail: "11",
    new: 1,
    discount: 0.9,
  },
  {
    pid: 4,
    src: "/Picture/hoagia4.png",
    title: "Hoa hồng lẻ",
    content: 25000,
    mota: "hoa được làm từ nhựa dẻo, có mùi hương nhân tạo an toàn cho sức khỏe 1 pack gồm 4 hoa nhỏ",
    detail: "12",
    new: 0,
    discount: 0,
  },
  {
    pid: 5,
    src: "/Picture/hoatuoile1.png",
    title: "Hoa tuylip tách lẻ",
    content: 20000,
    mota: "hoa tươi được nhập trực tiếp từ cánh đồng với nhiều màu sắc cam, vàng, đỏ",
    detail: "13",
    new: 1,
    discount: 0,
  },
  {
    pid: 5,
    src: "/Picture/hoatuoile2.png",
    title: "Hoa hướng dương tách lẻ",
    content: 20000,
    mota: "Hoa hướng dương cỡ lớn được trang trí kèm một số hoa mini",
    detail: "14",
    new: 0,
    discount: 0,
  },
  {
    pid: 5,
    src: "/Picture/hoatuoile3.png",
    title: "Hoa vân môn tách lẻ",
    content: 20000,
    mota: "Với màu trắng tinh khiết, hoa vân môn thích hợp cho cô dâu trong ngày cưới",
    detail: "15",
    new: 0,
    discount: 0,
  },
  {
    pid: 5,
    src: "/Picture/hoatuoile4.png",
    title: "Hoa hồng tách lẻ",
    content: 20000,
    mota: "Những đóa hoa hồng được lựa chọn kỹ càng , luôn đạt yêu cầu về độ tươi",
    detail: "16",
    new: 0,
    discount: 0,
  },
  {
    pid: 6,
    src: "/Picture/hoacodau2.png",
    title: "Hoa cô dâu tông trắng",
    content: 20000,
    mota: "Bó hoa là sự phối hợp của các loại hoa trắng, đem lại sự tươi sáng cho cô dâu",
    detail: "17",
    new: 0,
    discount: 0.9,
  },
  {
    pid: 6,
    src: "/Picture/hoabo1.png",
    title: "Hoa bó tông hồng",
    content: 20000,
    mota: "Một bó hoa tông màu chủ đạo là hồng bao gồm nhiều loại hoa hồng, hoa thược dược...",
    detail: "18",
    new: 0,
    discount: 0.9,
  },
  {
    pid: 6,
    src: "/Picture/hoabo2.png",
    title: "Hoa bó mùa hè",
    content: 20000,
    mota: "Bó hoa với sự kết hợp giữa hướng dương và hồng trắng tạo nên sự rực rỡ của mùa hè",
    detail: "19",
    new: 1,
    discount: 0.85,
  },
  {
    pid: 6,
    src: "/Picture/hoabo4.png",
    title: "Hoa tặng người yêu",
    content: 20000,
    mota: "Bó hoa được cắm tỉ mĩ là một món quà thật tuyệt với để tặng cho người yêu",
    detail: "20",
    new: 0,
    discount: 0.85,
  },
  {
    pid: 7,
    src: "/Picture/hoabo6.png",
    title: "Hy vọng",
    content: 20000,
    mota: "Bó hoa tông màu xanh, màu của nìm tin và hy vọng",
    detail: "21",
    new: 0,
    discount: 0.85,
  },
  {
    pid: 7,
    src: "/Picture/tinhyeu.png",
    title: "Tình yêu",
    content: 20000,
    mota: "Với tông màu đỏ và hồng nhạt, bó hoa thể hiện tình yêu to lớn dành cho đối phương",
    detail: "22",
    new: 0,
    discount: 0,
  },
  {
    pid: 7,
    src: "/Picture/yeuthuong.png",
    title: "Yêu thương",
    content: 20000,
    mota: "Với thiết kế chỉnh chu, Bó hoa thể hiện sự quý mến của mình đối với người nhận",
    detail: "23",
    new: 0,
    discount: 0,
  },
  {
    pid: 7,
    src: "/Picture/mocmac.png",
    title: "Mộc mạc",
    content: 20000,
    mota: "Tông màu chủ yếu là trắng và xanh lá, Màu sắc của sự nhẹ nhàng và mộc mạc",
    detail: "24",
    new: 1,
    discount: 0,
  },
];
